Repository boostcampwm-2024/web36-QLab, pull requests merged in 2024-11, with the labels that each got.

#49 [#6] 전체 레이아웃을 만든다
  FE/.eslintrc.json
  FE/components.json
  FE/package-lock.json
  FE/package.json
  FE/postcss.config.js
  FE/src/App.tsx
  FE/src/assets/logo.svg
  FE/src/components/AppSidebar.tsx
  FE/src/components/NavUser.tsx
  FE/src/components/Shell.tsx
  FE/src/components/ui/avatar.tsx
  FE/src/components/ui/badge.tsx
  FE/src/components/ui/button.tsx
  FE/src/components/ui/collapsible.tsx
  FE/src/components/ui/dropdown-menu.tsx
  FE/src/components/ui/input.tsx
  FE/src/components/ui/label.tsx
  FE/src/components/ui/separator.tsx
  FE/src/components/ui/sheet.tsx
  FE/src/components/ui/sidebar.tsx
  FE/src/components/ui/skeleton.tsx
  FE/src/components/ui/tooltip.tsx
  FE/src/hooks/use-mobile.tsx
  FE/src/index.css
  FE/src/lib/utils.ts
  FE/src/mocData.ts
  FE/src/pages/MainPage.tsx
  FE/src/types/declaration.d.ts
  FE/tailwind.config.js
  FE/tsconfig.json
  FE/vite.config.ts
Labels: FE

#53 [#23] 쿼리에 대한 결과값을 반환한다.
  be/src/common/enums/query-type.enum.ts
  be/src/common/response/response.dto.ts
  be/src/infrastructure/query-database/query-db.adapter.ts
  be/src/infrastructure/query-database/query-db.moudle.ts
  be/src/infrastructure/query-database/single-mysql.adapter.ts
  be/src/query/dto/query.dto.ts
  be/src/query/dto/res-query.dto.ts
  be/src/query/query.controller.ts
  be/src/query/query.module.ts
  be/src/query/query.service.ts
Labels: BE

#54 [#46,47,48] 쉘 추가, 수정, 삭제
  be/package.json
  be/src/common/exception/exception.handler.ts
  be/src/main.ts
  be/src/shell/dto/create-shell.dto.ts
  be/src/shell/dto/res-shell.dto.ts
  be/src/shell/dto/update-shell.dto.ts
  be/src/shell/shell.controller.ts
  be/src/shell/shell.entity.ts
  be/src/shell/shell.module.ts
  be/src/shell/shell.service.ts
  be/test/shell/shell.service.spec.ts
Labels: BE

#51 [#8] 결과 레이아웃을 만든다
  FE/src/pages/MainPage.tsx
Labels: FE

#56 [#9] 추가버튼을 통해 쉘을 추가한다
  FE/src/components/AppSidebar.tsx
  FE/src/components/Shell.tsx
  FE/src/components/ShellList.tsx
  FE/src/constants.ts
  FE/src/index.css
  FE/src/mocData.ts
  FE/src/mocdata.json
  FE/src/pages/MainPage.tsx
  FE/src/types/interfaces.ts
  FE/vite.config.ts
Labels: FE

#57 [#10] 삭제버튼을 통해 쉘을 삭제한다.
  FE/src/components/Shell.tsx
  FE/src/components/ShellList.tsx
  FE/src/components/ui/sidebar.tsx
Labels: FE

#60 [#12] 최초 접속시 사용자에게 세션을 부여한다.
  be/package-lock.json
  be/package.json
  be/src/app.module.ts
  be/src/common/exception/exception.handler.ts
  be/src/query/query.controller.ts
  be/src/session/session.middleware.ts
  be/src/shell/shell.controller.ts
  be/src/shell/shell.service.ts
Labels: BE

#59 제안 - ResponseDto 직렬화 인터셉터 사용
  be/.gitignore
  be/src/interceptors/serialize.interceptor.ts
Labels: BE

#63 jenkins 파일 추가
  be/Jenkinsfile
Labels: BE, INFRA

#72 chore : dev 브랜치 깃허브 PR 템플릿 추가
  .github/ISSUE_TEMPLATE/bug-tempalte.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: INFRA

#78 [#74] 도커 파일, 컴포즈 파일 작성
  FE/Dockerfile
  be/Dockerfile
  docker-compose.yml
  nginx/Dockerfile
  nginx/nginx.conf
Labels: INFRA

#80 [#68] npm start:container를 통해 도커로 실행될 수 있게 한다.
  .gitignore
  be/docker-compose.backend.local.yml
  package.json
Labels: BE

#86 [#18 #19] 서버에서 쿼리 실행 결과를 성공적으로 받으면 결과창에 결과를 띄운다.
  FE/src/components/Shell.tsx
  FE/src/components/ui/table.tsx
Labels: FE

#85 [#39] 쉘 실행시 쉘 실행 요청을 보낸다.
  FE/package-lock.json
  FE/src/api/__mocks__/axiosMock.ts
  FE/src/api/__mocks__/mocDataResult.json
  FE/src/api/__mocks__/mocdata.json
  FE/src/api/__mocks__/util.ts
  FE/src/api/axiosClient.ts
  FE/src/api/shellApi.ts
  FE/src/components/Shell.tsx
  FE/src/components/ShellList.tsx
  FE/src/hooks/useShellQuery.tsx
  FE/src/types/interfaces.ts
  FE/tsconfig.json
Labels: FE

#83 [#67] mysql adapter testcode 작성
  BE/package-lock.json
  BE/package.json
  BE/src/config/query-database/query-db.adapter.ts
  BE/src/config/query-database/single-mysql.adapter.ts
  BE/src/config/swagger/swagger.config.ts
  BE/src/query/query.service.ts
  BE/test/query/query.service.spec.ts
  be/test/query-database/query-database.spec.ts
Labels: BE

#84 [#66] 세션 관리(redis)에 대한 테스트 코드를 작성한다.
  BE/package-lock.json
  BE/package.json
  BE/src/app.module.ts
  BE/src/config/redis/redis.module.ts
  BE/src/config/redis/redis.service.ts
  BE/src/session/session.middleware.ts
  BE/test/query/redis.spec.ts
Labels: BE

#88 [#87] 쉘 전체, id로 하나의 쉘 조회
  BE/src/config/redis/redis.client.ts
  BE/src/interceptors/serialize.interceptor.ts
  BE/src/shell/shell.controller.ts
  BE/src/shell/shell.service.ts
Labels: BE

#82 [#44] main 브랜치에 merge 시 자동으로 서버에 배포한다.
  BE/Dockerfile
  FE/Dockerfile
  Jenkinsfile
  docker-compose.yml
Labels: INFRA

#100 [#17] 쿼리 실행시간 측정, 세션 오류 발견 및 수정
  BE/src/app.module.ts
  BE/src/common/exception/exception.handler.ts
  BE/src/config/query-database/query-db.adapter.ts
  BE/src/config/query-database/single-mysql.adapter.ts
  BE/src/config/redis/redis.service.ts
  BE/src/guard/guard.module 2.ts
  BE/src/guard/shell.guard 2.ts
  BE/src/middleware/session.middleware.ts
  BE/src/query/query.service.ts
  BE/test/session/redis.service.spec.ts
  BE/test/shell/shell.service.spec.ts
Labels: BE

#122 [#45] dev 브랜치에 merge 시 테스트 자동화를 구축한다.
  FE/Dockerfile
  Jenkinsfile
Labels: INFRA, test

#123 [#115] 변경된 api에 따라 쿼리 결과 출력 로직을 수정한다.
  FE/src/api/__mocks__/axiosMock.ts
  FE/src/api/__mocks__/mocDataResult.json
  FE/src/api/__mocks__/mocdata.json
  FE/src/api/__mocks__/util.ts
  FE/src/api/shellApi.ts
  FE/src/components/Shell.tsx
  FE/src/components/ShellList.tsx
  FE/src/mocdata.json
  FE/src/pages/MainPage.tsx
  FE/src/types/interfaces.ts
  FE/src/util.ts
Labels: FE

#126 [#114] input 두번 눌러야 포커스 되는 이슈 해결
  FE/src/api/__mocks__/axiosMock.ts
  FE/src/components/Shell.tsx
  FE/src/components/ShellList.tsx
  FE/src/hooks/useCustomMutation.ts
  FE/src/util.ts
Labels: FE

#128 [#101, #113] 쉘 창 리팩토링
  FE/src/components/Shell.tsx
Labels: FE

#125 [#27] 전체 테이블 정보 및 특정 테이블 정보 가져오기
  BE/BE.iml
  BE/src/app.module.ts
  BE/src/config/query-database/query-db.adapter.ts
  BE/src/config/query-database/single-mysql.adapter.ts
  BE/src/config/redis/redis.service.ts
  BE/src/config/service-database/service-db.module.ts
  BE/src/config/swagger/table-swagger.decorator.ts
  BE/src/session/session.middleware.ts
  BE/src/shell/shell.entity.ts
  BE/src/shell/shell.service.ts
  BE/src/table/dto/res-table.dto.ts
  BE/src/table/dto/res-tables.dto.ts
  BE/src/table/table.controller.ts
  BE/src/table/table.module.ts
  BE/src/table/table.service.ts
Labels: BE

#132 [#116] 쿼리 타입 분기
  BE/src/common/enums/query-type.enum.ts
  BE/src/config/query-database/single-mysql.adapter.ts
  BE/src/config/redis/redis.service.ts
  BE/src/config/service-database/service-db.module.ts
  BE/src/query/query.service.ts
  BE/src/shell/shell.service.ts
  BE/test/query/query.service.spec.ts
Labels: BE

#131 [#102,#105] 테이블 생성,수정에 대해서 SQL로 변환한다.
  FE/src/util.ts
Labels: FE

#135 [#118] 테이블 보기 레이아웃을 만든다. (버튼, 사이드 창)
  FE/src/api/__mocks__/mocDataTable.json
  FE/src/components/LeftSidebar.tsx
  FE/src/components/NavUser.tsx
  FE/src/components/RightSidebar.tsx
  FE/src/components/ViewTable.tsx
  FE/src/constants.ts
  FE/src/pages/MainPage.tsx
  FE/src/types/interfaces.ts
Labels: FE

#138 [ #119] 테이블 데이터를 요청하고 화면에 띄운다.
  FE/src/api/__mocks__/axiosMock.ts
  FE/src/api/__mocks__/mockShells.ts
  FE/src/api/__mocks__/mockTables.ts
  FE/src/api/tableApi.ts
  FE/src/components/RightSidebar.tsx
  FE/src/components/ViewTable.tsx
  FE/src/constants.ts
  FE/src/hooks/useShellQuery.tsx
  FE/src/hooks/useTableQuery.ts
  FE/src/pages/MainPage.tsx
  FE/src/types/interfaces.ts
Labels: FE

#139 [#120] 테이블이 변경되는 쿼리 실행시 해당 테이블의 정보를 가져온다.
  FE/src/api/__mocks__/mockTables.ts
  FE/src/api/tableApi.ts
  FE/src/components/Shell.tsx
  FE/src/components/ViewTable.tsx
  FE/src/constants.ts
  FE/src/hooks/useShellQuery.tsx
  FE/src/hooks/useTableQuery.ts
Labels: FE

#137 [#108, #110] 사용자로부터 데이터 추가 요청을 받고 결과를 반환한다.
  .gitignore
  BE/.eslintrc.js
  BE/.gitignore
  BE/docker-compose.backend.local.yml
  BE/src/config/query-database/single-mysql.adapter.ts
  BE/src/query/query.service.ts
  BE/src/record/domain/boolean.ts
  BE/src/record/domain/city.ts
  BE/src/record/domain/country.ts
  BE/src/record/domain/email.ts
  BE/src/record/domain/enum.ts
  BE/src/record/domain/index.ts
  BE/src/record/domain/name.ts
  BE/src/record/domain/number.ts
  BE/src/record/domain/phone.ts
  BE/src/record/domain/random-value-generator.interface.ts
  BE/src/record/domain/sex.ts
  BE/src/record/dto/record.dto.ts
  BE/src/record/randomColumn.entity.ts
  BE/src/record/record.controller.ts
  BE/src/record/record.module.ts
  BE/src/record/record.service.ts
  BE/tsconfig.json
Labels: BE

#144 [#104] 테이블 추가 레이아웃을 만든다.
  FE/package-lock.json
  FE/package.json
  FE/src/components/LeftSidebar.tsx
  FE/src/components/TableTool.tsx
  FE/src/components/ui/checkbox.tsx
  FE/src/components/ui/dialog.tsx
  FE/src/components/ui/select.tsx
  FE/src/constants.ts
  FE/src/pages/MainPage.tsx
  FE/src/types/interfaces.ts
  FE/src/util.ts
Labels: FE

#165 feat : q-lab.site 접속 시 www.q-lab.site 로 리디렉션 되도록 처리
  nginx/nginx.conf
Labels: BE

#149 [#127] 부하 테스트진행
  BE/src/config/query-database/query-db.adapter.ts
  BE/src/middleware/session.middleware.ts
  BE/src/query/query.service.ts
  BE/src/record/record.controller.spec.ts
  BE/src/record/record.service.spec.ts
  BE/src/table/table.service.ts
  load-test/chart.py
  load-test/locustfile.py
  package-lock 2.json
Labels: test

#168 [#103] 새로운 쉘을 생성하고, 해당 쉘에 쿼리문을 넣어준다.
  FE/src/api/shellApi.ts
  FE/src/components/EditableInput.tsx
  FE/src/components/Shell.tsx
  FE/src/components/ShellList.tsx
  FE/src/components/TableTool.tsx
  FE/src/components/ViewTable.tsx
  FE/src/hooks/useShellHandler.ts
  FE/src/hooks/useShellQuery.tsx
  FE/src/util.ts
Labels: FE

#167 [#166] 쉘 입력시 에디터를 적용한다
  FE/package-lock.json
  FE/package.json
  FE/src/components/LeftSidebar.tsx
  FE/src/components/Shell.tsx
  FE/src/components/ShellList.tsx
  FE/vite.config.ts
Labels: FE

#169 [#164] https 적용
  docker-compose.yml
  nginx/Dockerfile
  nginx/nginx.conf
Labels: INFRA

#170 ver 1.1.2
  BE/package-lock.json
  BE/package.json
  BE/src/config/query-database/query-db.adapter.ts
  BE/src/config/query-database/query-db.moudle.ts
  BE/src/config/query-database/single-mysql-connection-manager.ts
  BE/src/config/query-database/single-mysql.adapter.ts
  BE/src/config/redis/redis.service.ts
  BE/src/middleware/session.middleware.ts
  BE/src/query/query.service.ts
  BE/src/record/record.controller.spec.ts
  BE/src/record/record.service.spec.ts
  BE/src/record/record.service.ts
  BE/src/table/table.service.ts
  FE/package-lock.json
  FE/package.json
  FE/src/api/shellApi.ts
  FE/src/components/EditableInput.tsx
  FE/src/components/LeftSidebar.tsx
  FE/src/components/Shell.tsx
  FE/src/components/ShellList.tsx
  FE/src/components/TableTool.tsx
  FE/src/components/ViewTable.tsx
  FE/src/hooks/useShellHandler.ts
  FE/src/hooks/useShellQuery.tsx
  FE/src/util.ts
  FE/vite.config.ts
  docker-compose.yml
  load-test/chart.py
  load-test/locustfile.py
  nginx/Dockerfile
  nginx/nginx.conf
  package-lock 2.json
Labels: deploy

#174 [#173] 자동 줄 바꿈 구현 및 font size 조절
  BE/package-lock.json
  FE/src/components/Shell.tsx
Labels: FE

#175 [#158, #159] 예시 쿼리 클릭시 쉘에 해당 쿼리를 넣어준다.
  FE/.eslintrc.json
  FE/.prettierrc
  FE/src/components/LeftSidebar.tsx
  FE/src/components/RightSidebar.tsx
  FE/src/components/TableTool.tsx
  FE/src/components/TestTool.tsx
  FE/src/components/ui/textarea.tsx
  FE/src/constants/constants.ts
  FE/src/constants/exampleQuery.ts
  FE/src/hooks/useShellQuery.tsx
  FE/src/hooks/useTableQuery.ts
  FE/src/pages/MainPage.tsx
  FE/src/types/interfaces.ts
Labels: FE

#177 [#155] 스토리지 사용량 UI 레이아웃
  FE/src/components/CapacityUsage.tsx
  FE/src/components/ShellList.tsx
  FE/src/components/TestTool.tsx
  FE/src/constants/constants.ts
  FE/src/types/interfaces.ts
Labels: FE

#178 [#153] 사용자 db connection생성에 따른 제거
  BE/src/app.module.ts
  BE/src/config/cors/cors.config.ts
  BE/src/config/query-database/admin-db-manager.service.ts
  BE/src/config/query-database/admin-query-db.moudle.ts
  BE/src/config/query-database/query-db.adapter.ts
  BE/src/config/query-database/query-db.moudle.ts
  BE/src/config/query-database/single-mysql-connection-manager.ts
  BE/src/config/query-database/single-mysql.adapter.ts
  BE/src/config/query-database/user-db-manager.service.ts
  BE/src/config/redis/custom-redis-store.ts
  BE/src/config/redis/redis.module.ts
  BE/src/config/redis/redis.service.ts
  BE/src/config/swagger/record-swagger.decorator.ts
  BE/src/config/swagger/table-swagger.decorator.ts
  BE/src/interceptors/user-db-connection.interceptor.ts
  BE/src/middleware/session.middleware.ts
  BE/src/query/query.controller.ts
  BE/src/query/query.module.ts
  BE/src/query/query.service.ts
  BE/src/record/constant/random-record.constant.ts
  BE/src/record/domain/random-value-generator.interface.ts
  BE/src/record/dto/create-random-record.dto.ts
  BE/src/record/dto/res-record.dto.ts
  BE/src/record/random-column.entity.ts
  BE/src/record/record.controller.ts
  BE/src/record/record.module.ts
  BE/src/record/record.service.ts
  BE/src/table/dto/res-table.dto.ts
  BE/src/table/dto/res-tables.dto.ts
  BE/src/table/table.controller.ts
  BE/src/table/table.module.ts
  BE/src/table/table.service.ts
  BE/src/usage/usage.module.ts
  BE/src/usage/usage.service.ts
  BE/src/usage/useage.module.ts
  BE/src/user/user.controller.spec.ts
  BE/src/user/user.service.spec.ts
  BE/test/query-database/query-database.spec.ts
  BE/test/query/query.service.spec.ts
  BE/test/session/redis.service.spec.ts
  nginx/nginx.conf
Labels: BE

#182 [#111] 랜덤 데이터 로직 추가
  FE/src/components/InputWithLocalState.tsx
  FE/src/components/RecordTool.tsx
  FE/src/components/TagInputForm.tsx
  FE/src/components/TestTool.tsx
  FE/src/constants/constants.ts
  FE/src/types/interfaces.ts
  FE/src/util.ts
Labels: FE

#184 [#156] 사용량 요청 api 연동
  FE/src/api/__mocks__/axiosMock.ts
  FE/src/api/__mocks__/mockUsages.ts
  FE/src/api/usageApi.ts
  FE/src/components/CapacityUsage.tsx
  FE/src/components/Shell.tsx
  FE/src/components/ShellList.tsx
  FE/src/constants/constants.ts
  FE/src/hooks/useUsageQuery.tsx
  FE/src/pages/MainPage.tsx
  FE/src/types/interfaces.ts
Labels: FE

#187 [#186] table 컬럼 타입 숫자까지 보이도록
  BE/src/config/query-database/admin-db-manager.service.ts
  BE/src/config/swagger/shell-swagger.decorator.ts
  BE/src/shell/shell.controller.ts
  BE/src/table/table.service.ts
Labels: BE

#190 [#183, #154] 랜덤 데이터 추가 요청을 보내고 추가 결과를 보여준다.
  FE/package-lock.json
  FE/package.json
  FE/src/api/__mocks__/axiosMock.ts
  FE/src/api/__mocks__/mockRecord.ts
  FE/src/api/recordApi.ts
  FE/src/components/RecordTool.tsx
  FE/src/components/Shell.tsx
  FE/src/components/TestTool.tsx
  FE/src/components/ui/toast.tsx
  FE/src/components/ui/toaster.tsx
  FE/src/hooks/use-toast.ts
  FE/src/hooks/useRecordQuery.ts
  FE/src/pages/MainPage.tsx
  FE/src/types/interfaces.ts
  FE/src/util.ts
Labels: FE

#194 [#21, #22] 결과테이블을 10개씩 보여주고, +버튼을 통해 10개씩 추가 추가한다.
  FE/src/components/ResultTable.tsx
  FE/src/components/Shell.tsx
Labels: FE

#193 [#152] 로깅 데이터를 수집한다.
  BE/docker-compose.backend.local.yml
  BE/package-lock.json
  BE/package.json
  BE/src/app.module.ts
  BE/src/config/logger/logger.module.ts
  BE/src/config/logger/logger.service.ts
  BE/src/config/logger/winston.config.ts
  BE/src/interceptors/logging.interceptor.ts
  BE/src/main.ts
  docker-compose.yml
Labels: BE

#195 [#188] 부하테스트 진행 및 userDB req직접 주입으로 변경
  BE/src/config/query-database/admin-query-db.moudle.ts
  BE/src/config/query-database/user-db-manager.service.ts
  BE/src/config/redis/redis.module.ts
  BE/src/guard/guard.module.ts
  BE/src/query/query.controller.ts
  BE/src/query/query.service.ts
  BE/src/record/record.controller.ts
  BE/src/record/record.module.ts
  BE/src/record/record.service.ts
  BE/src/shell/shell.module.ts
  BE/src/table/table.module.ts
  BE/src/usage/usage.controller.ts
  BE/src/usage/usage.module.ts
  BE/src/usage/usage.service.ts
Labels: BE, test, refactor

#205 [#197] 헤더 고정
  FE/src/components/ShellList.tsx
  FE/src/pages/MainPage.tsx
Labels: FE

#206 [#198, #199] 새로고침하고 쉘 크기가 다시 작아지는 이슈 수정
  FE/src/components/Shell.tsx
  FE/src/constants/constants.ts
  FE/src/constants/exampleQuery.ts
Labels: FE

#207 [#200] input 더블클릭하는거 바꿔두기
  FE/src/components/EditableInput.tsx
  FE/src/components/TableTool.tsx
Labels: FE

#208 [#204] 프론트 에러핸들링 구현
  FE/src/api/__mocks__/mockRecord.ts
  FE/src/api/__mocks__/mockShells.ts
  FE/src/components/RecordTool.tsx
  FE/src/error/toastErrorHandler.ts
  FE/src/hooks/use-toast.ts
  FE/src/hooks/useCustomMutation.ts
  FE/src/hooks/useRecordQuery.ts
Labels: FE

#209 [#152] 로깅 폴더 위치 수정 및 보완
  BE/src/config/logger/logger.service.ts
  BE/src/interceptors/logging.interceptor.ts
  docker-compose.yml
Labels: BE, INFRA

#211 랜덤 데이터 추가 시 사용량 새로고침
  BE/src/usage/usage.service.ts
  FE/src/components/RecordTool.tsx
Labels: BE

#212 배포 2.0.2
  BE/src/usage/usage.service.ts
  FE/src/components/RecordTool.tsx
Labels: deploy
