Repository boostcampwm-2024/web36-QLab, pull requests merged in 2024-12, with the labels that each got.

#221 배포 2.0.5
  BE/src/config/logger/logger.service.ts
  BE/src/config/logger/winston.config.ts
  BE/src/interceptors/logging.interceptor.ts
  README.md
  load-test/__pycache__/locustfile.cpython-313.pyc
Labels: deploy

#215 [#201] UI 리팩토링: 쉘 추가하면 포커스 가게 변경
  FE/package-lock.json
  FE/package.json
  FE/src/api/__mocks__/mockRecord.ts
  FE/src/api/__mocks__/mockShells.ts
  FE/src/api/shellApi.ts
  FE/src/components/RecordTool.tsx
  FE/src/components/ResultTable.tsx
  FE/src/components/Shell.tsx
  FE/src/components/TableTool.tsx
  FE/src/components/TestTool.tsx
  FE/src/error/toastErrorHandler.ts
  FE/src/hooks/useShellHandler.ts
  FE/src/main.tsx
  FE/vite.config.ts
Labels: FE

#224 [#162] RedisService 테스트 코드 작성
  BE/package-lock.json
  BE/package.json
  BE/src/config/logger/logger.service.ts
  BE/src/config/query-database/admin-db-manager.service.ts
  BE/src/config/redis/redis.service.ts
  BE/src/middleware/session.middleware.ts
  BE/test/session/redis.service.spec.ts
  Jenkinsfile
Labels: BE, test

#226 [#216] 클라이엔트에서 에러가 발생한 경후 에러페이지를 보여준다.
  FE/package-lock.json
  FE/package.json
  FE/src/components/CapacityUsage.tsx
  FE/src/components/EditableInput.tsx
  FE/src/components/ExampleQueryTool.tsx
  FE/src/components/LeftSidebar.tsx
  FE/src/components/MainContent.tsx
  FE/src/components/RecordTool.tsx
  FE/src/components/RightSidebar.tsx
  FE/src/components/TableTool.tsx
  FE/src/components/ViewTable.tsx
  FE/src/components/common/InputWithLocalState.tsx
  FE/src/components/common/ResultTable.tsx
  FE/src/components/common/TagInputForm.tsx
  FE/src/components/common/shell/Shell.tsx
  FE/src/components/common/shell/ShellErrorFallback.tsx
  FE/src/components/ui/sidebar.tsx
  FE/src/hooks/error/toastErrorHandler.ts
  FE/src/hooks/query/useCustomMutation.ts
  FE/src/hooks/query/useRecordQuery.ts
  FE/src/hooks/query/useShellQuery.tsx
  FE/src/hooks/query/useTableQuery.ts
  FE/src/hooks/query/useUsageQuery.tsx
  FE/src/hooks/useIsMobile.tsx
  FE/src/hooks/useShellHandler.ts
  FE/src/pages/MainErrorPage.tsx
  FE/src/pages/MainPage.tsx
  FE/src/pages/SideBarErrorPage.tsx
Labels: FE

#223 [#222] Request Validation 에 활용할 zod 스키마 정의
  BE/package-lock.json
  BE/package.json
  package-lock.json
  package.json
  schemas/index.ts
  schemas/query.ts
  schemas/record.ts
  schemas/shells.ts
Labels: FE

#228 [#15] 쉘 실행시 로딩중임을 유저에게 보여준다.
  FE/src/components/common/ResultTable.tsx
  FE/src/components/common/shell/Shell.tsx
Labels: FE

#232 [#225] 로딩 화면을 추가한다
  FE/src/components/LeftSidebar.tsx
  FE/src/components/MainContent.tsx
  FE/src/components/RightSidebar.tsx
  FE/src/pages/LoadingPage.tsx
  FE/src/pages/MainPage.tsx
  FE/tailwind.config.js
Labels: FE

#231 [#227] 세션 만료 시간 갱신
  BE/src/config/logger/winston.config.ts
  BE/src/config/redis/custom-redis-store.ts
  BE/src/config/redis/redis.service.ts
  BE/src/middleware/session.middleware.ts
Labels: BE

#235 [#220] sessionID와 스키마명 분리
  BE/src/config/query-database/admin-db-manager.service.ts
  BE/src/interceptors/user-db-connection.interceptor.ts
  BE/src/table/table.service.ts
Labels: BE

#234 [#233] 네스트와 ZOD 를 활용해서 인풋 검증 연동하기
  BE/Dockerfile
  BE/Dockerfile.test
  BE/docker-compose.backend.local.yml
  BE/ecosystem.config.js
  BE/nest-cli.json
  BE/package-lock.json
  BE/package.json
  BE/src/app.module.ts
  BE/src/common/exception/exception.handler.ts
  BE/src/query/dto/query.dto.ts
  BE/src/query/query.controller.ts
  BE/src/record/dto/create-random-record.dto.ts
  BE/src/record/random-column.entity.ts
  BE/src/shell/dto/update-shell.dto.ts
  Jenkinsfile
  docker-compose.yml
  package-lock.json
  package.json
  schemas/record.ts
Labels: BE

#236 [#189] 요청을 보내기 전, 사용자 입력을 검증한다
  FE/package-lock.json
  FE/package.json
  FE/src/components/RecordTool.tsx
  FE/src/components/TableTool.tsx
  FE/src/components/common/shell/Shell.tsx
  FE/src/constants/constants.ts
  FE/src/types/interfaces.ts
  FE/src/util.ts
  FE/tsconfig.json
  FE/vite.config.ts
  schemas/index.ts
Labels: FE

#238 [#237] zod 적용으로 인한 프로젝트 구조 변경에 따라 도커파일 수정
  BE/Dockerfile.test
  FE/Dockerfile
  FE/Dockerfile.test
  Jenkinsfile
  docker-compose.yml
  schemas/index.ts
Labels: BE

#241 [#161] record service 테스트 코드 작성
  BE/src/record/file.service.ts
  BE/src/record/record.module.ts
  BE/src/record/record.service.ts
  BE/src/usage/usage.service.ts
  BE/test/interceptor/user-db-connection.interceptor.spec.ts
  BE/test/query-database/query-database.spec.ts
  BE/test/record/record.service.spec.ts
Labels: BE, test, refactor

#244 배포 2.1.0
  FE/src/components/CapacityUsage.tsx
  FE/src/components/RecordTool.tsx
Labels: deploy

#250 [#249] LOAD DATA 분산처리
  BE/src/record/constant/random-record.constant.ts
  BE/src/record/file.service.ts
  BE/src/record/record.service.ts
Labels: BE

#251 배포 2.1.4
  BE/src/record/constant/random-record.constant.ts
  BE/src/record/file.service.ts
  BE/src/record/record.service.ts
  README.md
Labels: deploy

#252 베포 2.1.5
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  BE/.gitignore
  BE/src/record/file.service.ts
Labels: deploy

#253 배포 2.1.6
  BE/src/config/query-database/user-db-manager.service.ts
  BE/src/record/constant/random-record.constant.ts
  BE/src/record/file.service.ts
  BE/src/record/record.service.ts
  web36-QLab.iml
Labels: deploy

#255 배포 2.1.8
  BE/src/config/query-database/user-db-manager.service.ts
  BE/src/record/file.service.ts
  BE/src/record/record.service.ts
  FE/src/util.ts
Labels: deploy
